services:
  db:
    image: mariadb
    container_name: pmmmp_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: pmmp
      MARIADB_PASSWORD: pmmp

  pmmp:
    image: pmmp/pocketmine-mp:latest
    container_name: pmmp
    ports:
      - 19132:19132/udp
    restart: always
    environment:
      POCKETMINE_PLUGINS: DevTools
    depends_on:
      - db
