name: CoralReef
main: ree_jp\coral_reef\CoralReefPlugin
api: 4.0.0
author: Ree-jp
website: https://reef.ree-jp.net/
version: 1.7.13
depend:
  - ReefEdge
  - BboForm
  - StackStorage
  - CustomItemLoader
permissions:
  coral_reef.command.menu:
    default: true
  coral_reef.command.block_log:
    default: true
  coral_reef.command.trash:
    default: true
  coral_reef.command.reef_admin:
    default: op
  coral_reef.command.reef_console:
    default: op
