name: CoralReef
main: ree_jp\coral_reef\CoralReefPlugin
api: 3.0.0
author: Ree-jp
website: https://reef.ree-jp.net/
version: 0.0.1
depend:
  - BboForm
  - StackStorage
permissions:
  coral_reef.*:
    default: false
    children:
      coral_reef.command.*:
        default: false
        children:
          coral_reef.command.reef_admin:
            default: op