name: "Build and Upload"
description: "build and upload"
inputs:
  build_info:
    description: "build information"
    required: true
  upload_name:
    description: "upload artifact name"
    required: true

runs:
  using: "composite"
  steps:
    - run: php -d phar.readonly=0 ./build/make-phar.php ${{ inputs.build_info }}
      shell: bash

    - run: wget https://cloud.ree-jp.net/s/qJTiJ8xZTDPa3xC/download -O libasynql.phar
      shell: bash
    - run: php -d phar.readonly=0 libasynql.phar ./build/CoralReef.phar "ree_jp\\coral_reef\\libs\\"
      shell: bash

    - run: wget https://cloud.ree-jp.net/s/mks8DgDiLH29eTj/download -O InvMenu.phar
      shell: bash
    - run: php -d phar.readonly=0 InvMenu.phar ./build/CoralReef.phar "ree_jp\\coral_reef\\libs\\"
      shell: bash

    - run: wget https://cloud.ree-jp.net/s/TSQtqd7nS4r7q8W/download -O await-generator.phar
      shell: bash
    - run: php -d phar.readonly=0 await-generator.phar ./build/CoralReef.phar "ree_jp\\coral_reef\\libs\\"
      shell: bash

    - run: wget https://cloud.ree-jp.net/s/AF8X3Gb3b8YBMpn/download -O bossbarapi.phar
      shell: bash
    - run: php -d phar.readonly=0 bossbarapi.phar ./build/CoralReef.phar "ree_jp\\coral_reef\\libs\\"
      shell: bash

    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.upload_name }}
        path: |
          ./build/*
          !./build/make-phar.php
