name: Auto Merge
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - plugin.yml
jobs:
  merge:
    name: Merge and deploy
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip]')"
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: stable

      - name: Merge master to stable
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git fetch
          git merge --allow-unrelated-histories origin/master

      - name: Push
        run: git push

      # Github Actionsからどう頑張っても別のActionsを起動できなかったからかなしくなってdeployも一緒に書く

      - name: build
        run: php -d phar.readonly=0 ./build/make-phar.php ${{ github.run_number }}-${GITHUB_REF##*/}

      - name: virion install
        run: |
          wget https://poggit.pmmp.io/r/152920/libasynql.phar -O libasynql.phar
          php -d phar.readonly=0 libasynql.phar ./build/CoralReef.phar "ree_jp\\coral_reef\\libs\\"
          wget https://poggit.pmmp.io/r/154019/InvMenu.phar -O InvMenu.phar
          php -d phar.readonly=0 InvMenu.phar ./build/CoralReef.phar "ree_jp\\coral_reef\\libs\\"

      - name: prepare deploy
        run: |
          mkdir ~/install_plugins
          mv ./build/CoralReef.phar ./install_plugins/CoralReef.phar

      - name: deploy seichi_1
        uses: sand4rt/ftp-deployer@v1.3
        with:
          sftp: true
          host: ${{ secrets.SEICHI_1_HOST }}
          port: ${{ secrets.SEICHI_1_PORT}}
          username: ${{ secrets.SEICHI_1_USERNAME }}
          password: ${{ secrets.SEICHI_1_PASSWORD }}
          remote_folder: /install_plugins/
          local_folder: ./install_plugins/
          cleanup: false
          inclued: |
            '*.phar'
