name: Feature Merge

on:
  push:
    branches:
      - "feature/*"
      - "test/*"
      - "fix/*"
  workflow_dispatch:

jobs:
  merge_feature:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[feature]') || contains(github.event.head_commit.message, '[fix]')"
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Create pull request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: ":sparkles: ${{github.ref_name}}"

      - name: Merge pull request
        run: |
          sleep 1s
          gh pr merge ${{ steps.pr.outputs.pr_url }} --auto --squash
